{
	"schema_version": "1.6.0",
	"id": "OSV-2022-1276",
	"modified": "2025-01-15T14:09:20.446847Z",
	"published": "2023-06-15T14:01:52.594793Z",
	"summary": "Stack-buffer-overflow in ntlm_phase_3",
	"details": "OSS-Fuzz report: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=59818\n\n```\nCrash type: Stack-buffer-overflow WRITE 1\nCrash state:\nntlm_phase_3\nestablish_http_proxy_passthru\nfuzz_proxy.c\n```\n",
	"affected": [
		{
			"package": {
				"ecosystem": "OSS-Fuzz",
				"name": "openvpn",
				"purl": "pkg:generic/openvpn"
			},
			"ranges": [
				{
					"type": "GIT",
					"repo": "https://github.com/OpenVPN/openvpn",
					"events": [
						{
							"introduced": "c768ee96b49a3df459f584d6050802312815deec"
						}
					]
				}
			],
			"versions": [
				"contains",
				"v2.6.0",
				"v2.6.1",
				"v2.6.2",
				"v2.6.3",
				"v2.6.4",
				"v2.6.5",
				"v2.6.6",
				"v2.6_beta1",
				"v2.6_beta2",
				"v2.6_branched",
				"v2.6_rc1",
				"v2.6_rc2",
				"v2.6.7",
				"v2.6.8",
				"v2.6.9",
				"v2.6.10",
				"v2.6.11",
				"v2.6.12",
				"v2.6.13"
			],
			"ecosystem_specific": {
				"severity": "HIGH"
			},
			"database_specific": {
				"source": "https://github.com/google/oss-fuzz-vulns/blob/main/vulns/openvpn/OSV-2022-1276.yaml"
			}
		}
	],
	"references": [
		{
			"type": "REPORT",
			"url": "https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=59818"
		}
	]
}
